name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v2

      - name: Deploy para GitHub Pages
        run: |
          git checkout gh-pages  # Troque para o nome da sua branch do GitHub Pages, geralmente "gh-pages"
          git rm -rf .         # Remove todos os arquivos na branch gh-pages
          cp -r * .            # Copia todos os arquivos do root para a branch gh-pages
          git add .
          git commit -m "Deployed via GitHub Actions"
          git push origin gh-pages:gh-pages
